### ISSUE TITLE
Setup instructions are out of date

### ISSUE THREAD

**Issue by joejuzl** [airware/vili#62]
Step 7. of the setup instructions states you should create a replication controller. The example link points to a 404. 
I'm guessing that this is due to the change to a kubernetes deployment?
If so, the step wording should be changed and it should link to: https://github.com/airware/vili/blob/master/docs/examples/simple/deployment.yaml

Cheers,

Joe

**Comment by BrianBland** [comment]
Thanks, I guess we missed that when moving from replication controllers to the newer deployment model. Fixed by #63
