### ISSUE TITLE
Error when creating a feature environment (vili 2.0)

### ISSUE THREAD

**Issue by ChristopheBougere** [airware/vili#73]
When clicking on "Create" while creating a feature environment, the dialog box never closes or updates:

Instead, I have this error in the console:

![image](https://user-images.githubusercontent.com/1325474/27126010-7615bee4-50f6-11e7-8d4e-3602319fc64d.png)

This url `api/v1/environments?` returns a 500

**Comment by volkangurel** [comment]
@ChristopheBougere I believe this was fixed in a recent version of vili 2.0, can you try again?

**Comment by ChristopheBougere** [comment]
Yep thanks.
There are still some warnings, but nothing fatal...
![image](https://user-images.githubusercontent.com/1325474/28767280-552c68e8-75d3-11e7-8f41-ba6ff2c3771f.png)
